"""Export Tab — accountability partner report generation."""

from __future__ import annotations

from datetime import date

import streamlit as st


def _generate_report(progress) -> str:
    """Generate markdown accountability partner report."""
    completed = [d for d in progress.days.values() if d.completed]
    total_scores = [d.score or 0 for d in completed]
    avg_score = sum(total_scores) / len(total_scores) if total_scores else 0

    lines = [
        "# PM Shock Cycle Bootcamp — Accountability Report",
        f"",
        f"**Generated:** {date.today().isoformat()}",
        f"**Current Day:** {progress.current_day} / 30",
        f"",
        f"## Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Days completed | {len(completed)} / 30 |",
        f"| Average daily score | {avg_score:.0f}/80 |",
        f"| Total points | {progress.total_score:.0f} |",
        f"| Review streak | {progress.review_streak} days |",
        f"",
        f"## Weekly Grades",
        f"",
        f"| Week | Total | Grade | Misses | Artifact? |",
        f"|------|-------|-------|--------|-----------|",
    ]

    for wk in range(1, 5):
        w = progress.weeks.get(wk)
        if w:
            art = "✅" if w.artifact_shipped else "❌"
            lines.append(
                f"| {wk} | {w.total:.0f} | {w.grade or '—'} | {w.misses} | {art} |"
            )
        else:
            lines.append(f"| {wk} | — | — | — | — |")

    lines.extend(
        [
            f"",
            f"## Grade Distribution",
            f"",
        ]
    )

    grades = {"A": 0, "B": 0, "C": 0, "F": 0}
    for d in completed:
        g = d.grade or ""
        if g in grades:
            grades[g] += 1

    lines.append(f"| Grade | Count |")
    lines.append(f"|-------|-------|")
    for g in ("A", "B", "C", "F"):
        lines.append(f"| {g} | {grades[g]} |")

    lines.extend(
        [
            f"",
            f"## Daily Score Log",
            f"",
            f"| Day | Score | Grade | Quotas Hit |",
            f"|-----|-------|-------|------------|",
        ]
    )

    for i in range(1, progress.current_day):
        dp = progress.days.get(i)
        if dp and dp.completed:
            lines.append(f"| {i} | {dp.score:.0f} | {dp.grade or '—'} | {dp.quotas_hit}/6 |")
        elif dp:
            lines.append(f"| {i} | — | — | {dp.quotas_hit}/6 |")
        else:
            lines.append(f"| {i} | — | — | — |")

    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Auto-generated by PM Shock Cycle Bootcamp Web App*")

    return "\n".join(lines)


def render_export_tab() -> None:
    from bootcamp.state import PROGRESS

    progress = st.session_state.get(PROGRESS)
    if progress is None:
        st.info("No bootcamp data to export.")
        return

    st.subheader("Accountability Partner Report")
    st.caption(
        "Generate a markdown report to share with your accountability partner."
        "Includes all daily scores, weekly grades, and camp progress."
    )

    # ── Report preview ─────────────────────────────────────
    report = _generate_report(progress)

    with st.expander("📄 Report Preview", expanded=True):
        st.markdown(report)

    # ── Download ───────────────────────────────────────────
    st.download_button(
        label="📥 Download Report (.md)",
        data=report.encode("utf-8"),
        file_name=f"bootcamp-report-{date.today().isoformat()}.md",
        mime="text/markdown",
        type="primary",
        use_container_width=True,
    )

    # ── Camp score summary ─────────────────────────────────
    st.markdown("---")
    st.subheader("Camp Score Summary")

    completed = [d for d in progress.days.values() if d.completed]

    kcols = st.columns(4)
    with kcols[0]:
        st.metric("Days Done", f"{len(completed)}/30")
    with kcols[1]:
        st.metric("Total Points", f"{progress.total_score:.0f}")
    with kcols[2]:
        st.metric("Streak", f"{progress.review_streak} days")
    with kcols[3]:
        from bootcamp.scoring import CAMP_TARGET
        pct = min(100, int(progress.total_score / CAMP_TARGET * 100))
        st.metric("Camp Progress", f"{pct}%")

    # ── Export all scorecards ──────────────────────────────
    if completed:
        st.markdown("### Export All Scorecards")
        all_cards = []
        for i in range(1, progress.current_day):
            dp = progress.days.get(i)
            if dp and dp.completed:
                from bootcamp.data import load_scorecard_md
                card = load_scorecard_md(i)
                if card:
                    all_cards.append(f"---\n\n{card.get('preview', '')}")

        if all_cards:
            full_export = "\n\n".join(all_cards)
            st.download_button(
                label="📦 Export All Scorecards (.md)",
                data=full_export.encode("utf-8"),
                file_name=f"bootcamp-all-scorecards-{date.today().isoformat()}.md",
                mime="text/markdown",
                use_container_width=True,
            )
