[theme]
base = "light"
primaryColor = "#0a5a46"
backgroundColor = "#faf9f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f1112"
borderColor = "#e8eaed"
linkColor = "#185fa5"
baseRadius = "none"
buttonRadius = "none"
font = "DM Sans:https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap"
headingFont = "DM Sans:https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap"
codeFont = "DM Mono:https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&display=swap"
headingFontWeights = [700, 700, 700, 700, 700, 700]

[theme.sidebar]
backgroundColor = "#faf9f7"
secondaryBackgroundColor = "#ffffff"
